//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _VX_ACS_Administration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_VX_ACS_Administration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If you close Administrator without saving, your changes will be lost.  Are you sure you want to close?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera/Door relationship already exists.  A new entry will not be added..
        /// </summary>
        internal static string CameraDoorExists {
            get {
                return ResourceManager.GetString("CameraDoorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Camera is not associated with a door.
        /// </summary>
        internal static string CameraUUIDNotFound {
            get {
                return ResourceManager.GetString("CameraUUIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Continuum Database!.
        /// </summary>
        internal static string CannotConnectToContinuumDB {
            get {
                return ResourceManager.GetString("CannotConnectToContinuumDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Connect to VideoXpert!.
        /// </summary>
        internal static string CannotConnectToVx {
            get {
                return ResourceManager.GetString("CannotConnectToVx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create database table &apos;3PIVX_PlugInDefaultDoor&apos;..
        /// </summary>
        internal static string CannotCreateDatabaseTable {
            get {
                return ResourceManager.GetString("CannotCreateDatabaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this instance?.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Connect to Continuum Database!.
        /// </summary>
        internal static string ConnectToContinuumDB {
            get {
                return ResourceManager.GetString("ConnectToContinuumDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Connection to VideoXpert..
        /// </summary>
        internal static string ConnectVxSuccess {
            get {
                return ResourceManager.GetString("ConnectVxSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Connection to VideoXpert.  Switching may remove all configured Camera/Door Associations.  Do you wish to switch to this VideoXpert system?.
        /// </summary>
        internal static string ConnectVxSuccessSwitch {
            get {
                return ResourceManager.GetString("ConnectVxSuccessSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error occured. Please contact the administrator with the following information:\n\n.
        /// </summary>
        internal static string ContactAdministrator {
            get {
                return ResourceManager.GetString("ContactAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andover Continuum - Pelco VX Plug-In Admin.
        /// </summary>
        internal static string Continuum {
            get {
                return ResourceManager.GetString("Continuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuum is not installed on this workstation. Please use Admin to enter Continuum Database Settings manually..
        /// </summary>
        internal static string ContinuumRegistryNotFound {
            get {
                return ResourceManager.GetString("ContinuumRegistryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ContinuumSettings.txt&quot; not found.
        /// </summary>
        internal static string ContinuumSettingsNotFound {
            get {
                return ResourceManager.GetString("ContinuumSettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;DoorCamerasMap.txt&quot; not found.
        /// </summary>
        internal static string DoorCamerasMapNotFound {
            get {
                return ResourceManager.GetString("DoorCamerasMapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Size to Show Event List.
        /// </summary>
        internal static string EventListPixels {
            get {
                return ResourceManager.GetString("EventListPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Non-UI Error: Could not write the error to the event log. Reason: .
        /// </summary>
        internal static string FatalNonUIError {
            get {
                return ResourceManager.GetString("FatalNonUIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Green_Dot {
            get {
                object obj = ResourceManager.GetObject("Green_Dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data cannot be blank..
        /// </summary>
        internal static string InvalidBlankData {
            get {
                return ResourceManager.GetString("InvalidBlankData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data is invalid..
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License verification failed. Please check license and restart application..
        /// </summary>
        internal static string LicenseVerificationFailed {
            get {
                return ResourceManager.GetString("LicenseVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Size.
        /// </summary>
        internal static string MaxSize {
            get {
                return ResourceManager.GetString("MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Size.
        /// </summary>
        internal static string MinSize {
            get {
                return ResourceManager.GetString("MinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuum PlugIn Administration.
        /// </summary>
        internal static string PlugInAdmin {
            get {
                return ResourceManager.GetString("PlugInAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red_Dot {
            get {
                object obj = ResourceManager.GetObject("Red_Dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been saved!.
        /// </summary>
        internal static string SettingsHaveBeenSaved {
            get {
                return ResourceManager.GetString("SettingsHaveBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings NOT saved!  Please fix errors!.
        /// </summary>
        internal static string SettingsNotSaved {
            get {
                return ResourceManager.GetString("SettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; should be between {1} and {2}..
        /// </summary>
        internal static string SizeRange {
            get {
                return ResourceManager.GetString("SizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Table [dbo].[3PIVX_PlugInDefaultDoor]    Script Date: 12/03/2015 13:53:22 ******/
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[3PIVX_PlugInDefaultDoor]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///
        ///CREATE TABLE [dbo].[3PIVX_PlugInDefaultDoor](
        ///	[ObjectId] [int] IDENTITY(1,1) NOT NULL,
        ///	[CameraGuid] [nvarchar](50) NULL,
        ///	[DoorIdHi] [int] NULL,
        ///	[DoorIdLo] [int] NULL
        ///) ON [PRIMARY]
        ///
        ///END
        ///
        ///IF NOT EXISTS (SELECT * FROM s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThirdPISql {
            get {
                return ResourceManager.GetString("ThirdPISql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[3PIVX_Config]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///CREATE TABLE [dbo].[3PIVX_Config](
        ///	[A] [varchar](255) NULL,
        ///	[B] [varchar](255) NULL
        ///) ON [PRIMARY]
        ///END
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[3PIVX_Camera]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///CREATE TABLE [dbo].[3PIVX_Camera](
        ///	[3PIVX_Name] [varchar](80) NOT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThirdPISqlCreateTables {
            get {
                return ResourceManager.GetString("ThirdPISqlCreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string TruncateDone {
            get {
                return ResourceManager.GetString("TruncateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string TruncateSkipped {
            get {
                return ResourceManager.GetString("TruncateSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating Log Files ....
        /// </summary>
        internal static string TruncatingLogFiles {
            get {
                return ResourceManager.GetString("TruncatingLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured in the program. Application is exiting. \r\n.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VideoXPert Server has changed, do you wish to remove all Camera/Door associations and refresh the camera list?.
        /// </summary>
        internal static string VideoXPertServerChanged {
            get {
                return ResourceManager.GetString("VideoXPertServerChanged", resourceCulture);
            }
        }
    }
}
